#! /bin/bash

CHEAT_ENGINE_CT="$HOME/.local/bin/ER_TGA_v1.17.0.CT"
ERFPS2_LOG_PATH="$HOME/.local/share/Steam/steamapps/common/ELDEN RING/Game/erfps2.log"

DXC_PATH="/usr/bin/dxc/"

cargo build || exit 1
cd target/x86_64-pc-windows-msvc/debug || exit 1
mkdir -p .hotpatch && cp -u erfps2.dll .hotpatch/erfps2.dll

RUST_LOG=trace me3 launch -g er --disable-arxan --savefile DEV.sl2 --native .hotpatch/erfps2.dll "$@" \
    & tail -f "$ERFPS2_LOG_PATH" \
    & sleep 1.5s && protonhax run 1245620 "$CHEAT_ENGINE" "$CHEAT_ENGINE_CT"
